### ISSUE TITLE
Move to Deferred return type of doRequest

### ISSUE THREAD

**Issue by karussell** [graphhopper/directions-api-js-client#1]
After fixing the response in case of an error in the routing API we should switch to the simple deferred pipe. Or create workaround even before via [this info](http://eng.wealthfront.com/2012/12/jquerydeferred-is-most-important-client.html)

**Comment by boldtrn** [comment]
This seems seems to be a bit outdated. I think it would be nice to return a [Promise](https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Promise). This is part of ES6, though. WDYT?

**Comment by karussell** [comment]
Yes, sure :)
