### ISSUE TITLE
Graphhopper run time error “GraphHopperRouting is not a constructor”

### ISSUE THREAD

**Issue by MaryCooperGD** [graphhopper/directions-api-js-client#22]
I wanted to use graphhopper js client in my Ionic app, so following the instructions explained [here](https://github.com/graphhopper/directions-api-js-client) I have installed the package using npm, then tried to use the routing API.  
All I did was import this:
  
    import {graphhopper, GraphHopperRouting, GHInput} from 'graphhopper-js-api-client';

And then wrote:

    var defaultKey = "[key]";
    var profile = "foot";
    var host;
    var ghRouting = new GraphHopperRouting({key: defaultKey, host: host, vehicle:profile,elevation:false})
    
    ghRouting.addPoint(new GHInput(47.400905, 8.534317));
     ghRouting.addPoint(new GHInput(47.394108, 8.538265));

     ghRouting.doRequest().then(function(json){
       console.log("Result: " + json)
     }).catch(function(err){
       console.log(err.message)
     })

Exactly as the guide explained.  
When I run the code, the following error is shown:

    Runtime Error
     __WEBPACK_IMPORTED_MODULE_6_graphhopper_js_api_client__.GraphHopperRouting is not a constructor

**Comment by karussell** [comment]
Is the import statement something Ionic specific? Maybe we are not yet ionic-compatible? Do you know what is required for this?

**Comment by boldtrn** [comment]
> Is the import statement something Ionic specific?

AFAIK, the import statement is TypeScript. 

> import {graphhopper, GraphHopperRouting, GHInput} from 'graphhopper-js-api-client';

My assumption would be that you might need  a different import statement. 

I think you could try different options:
- `import * as GraphHopper from 'graphhopper-js-api-client';`
- `import GraphHopper from 'graphhopper-js-api-client';`

In both cases I think the routing would be accessible as GraphHopper.Routing and not GraphHopperRouting. The last time I was writing TypeScript is some time ago and I don't have a test environment at hand right now, so I am not sure if it will work :).

**Comment by MaryCooperGD** [comment]
Hi, I've tried both imports and changed to GraphHopper.Routing, but the error is still there. 
The import is typescript, yes, nothing Ionic - specific.

**Comment by MaryCooperGD** [comment]
Ok so, I've tried using `require` instead of using the import statement from Typescript; now the error is gone, but here's what console prints out:
![image](https://user-images.githubusercontent.com/12009396/29994429-3f23213e-8fcf-11e7-9758-447173d11d94.png)

   
This is the complete request:

    var defaultKey = "2770d027-3826-4bf4-afc9-9491e75c983a";
    var profile = "foot";
    var host;

    require('graphhopper-js-api-client')
    var GraphHopperRouting = require('graphhopper-js-api-client/src/GraphHopperRouting');
    var GHInput = require('graphhopper-js-api-client/src/GHInput');
 
    
     var ghRouting = new GraphHopperRouting({key: defaultKey, host: host, vehicle:profile,elevation:false})
    
    ghRouting.addPoint(47.400905, 8.534317);
     ghRouting.addPoint(47.394108, 8.538265);

     ghRouting.doRequest().then(function(json){
       console.log("Result: " + json)
     }).catch(function(err){
       console.log("Error "+ err.message)
     }) 

If I copy the url in the browser, it tells me that the error is that I have to pass at least one point.

**Comment by MaryCooperGD** [comment]
I've changed the code using require, since with the different import options it still didn't work.   
This way it worked:

    require('graphhopper-js-api-client')
    var GraphHopperRouting = require('graphhopper-js-api-client/src/GraphHopperRouting');
    var GHInput = require('graphhopper-js-api-client/src/GHInput');

Guess Typescript wasn't ok with the namespace. 
Now I got the result. How can I use it and visualize it on a map? I mean, I got the JSON, now how do I use it to see the route between points on a map? 
Also, this code:

    ghRouting.addPoint(new GHInput(47.400905, 8.534317));
    ghRouting.addPoint(new GHInput(47.394108, 8.538265));

works ok if I have just two points to route, but what if I have some, that a priori I do not know how many of them? Is there a way to add, let's say, an array of GHInput?

**Comment by boldtrn** [comment]
Glad that you were able to work it out :).

> but what if I have some, that a priori I do not know how many of them? Is there a way to add, let's say, an array of GHInput?

I would be fine with adding another method for that. You could always use a for loop to iterate over an array and call the addPoint method multiple times.

> How can I use it and visualize it on a map?

That's up to you :). You can have a look at [our sample code](https://github.com/graphhopper/directions-api-js-client/blob/master/js/demo.js#L117), we use Leaflet, but there are other js map libraries as well.
