### ISSUE TITLE
Host @CDN

### ISSUE THREAD

**Issue by boldtrn** [graphhopper/directions-api-js-client#24]
I think it would be a nice improvement to host the js-client at a CDN. An easy solution seems to be this [CDN](https://www.jsdelivr.com/?docs=gh). Another example would be [cdnjs](https://cdnjs.com/).

**Comment by MartinKolarik** [comment]
Since you project is already on npm, you can use this without any additional config: https://www.jsdelivr.com/package/npm/graphhopper-js-api-client

**Comment by boldtrn** [comment]
@MartinKolarik thanks, jsdelivr was actually my first link posted above :). Currently I also tend to use this, as this does not require any additional work from our site.
