### ISSUE TITLE
Tests Are Failing

### ISSUE THREAD

**Issue by boldtrn** [graphhopper/directions-api-js-client#34]
I guess we need a new key for the demo?

**Comment by karussell** [comment]
Devs seem to be lazy and keep using the key in the repo so we made the key in the repo invalid (replacing it with a proper one when we deploy it).

**Comment by boldtrn** [comment]
Ok sure makes sense. Should try using a key in the environment encrypted on travis?

**Comment by karussell** [comment]
Ah, yes!

**Comment by boldtrn** [comment]
Can you setup the secret for travis? I will see if I can use it in the tests afterwards.
