### ISSUE TITLE
GHOptimization.js ignores shipments

### ISSUE THREAD

**Issue by oblonski** [graphhopper/directions-api-js-client#4]
it can only deal with services

**Comment by karussell** [comment]
I'll look into it

**Comment by karussell** [comment]
You already assigned to this issue - or should I look into it?

**Comment by oblonski** [comment]
I can do it :)

Am 16/07/15 um 09:16 schrieb Peter:

**Comment by karussell** [comment]
Will add a test for services so you can add it for shipments

**Comment by karussell** [comment]
Have added something to unit test our tools. See the spec on how I verified that the address is properly injected into the output from the input.

**Comment by karussell** [comment]
Fixed via https://github.com/graphhopper/directions-api-js-client/commit/6452324a5663c7bc0f335afe62516dc2c221fc75
