### ISSUE TITLE
Avoid sending parameters turn_sign_map.-3 etc

### ISSUE THREAD

**Issue by karussell** [graphhopper/directions-api-js-client#45]

**Comment by boldtrn** [comment]
Thanks for reporting this issue @karussell. Would you mind to add a brief description what this issue is about, I think I don't understand it yet :)?

**Comment by karussell** [comment]
Was a bit short :)

So the client sends lots of `turn_sign_map.*` parameters, which I think are unnecessary and should be avoided for clarity and slightly reduced bandwidth as they seem to be proportional to the number of via points.

**Comment by boldtrn** [comment]
Ah I see, thanks for the explanation. 

The issues seems to be created [here](https://github.com/graphhopper/directions-api-js-client/blob/0dd130386dfbe132834a00f0d169ce81d3fe73c4/src/GraphHopperRouting.js#L138). The clone method copies all properties of an object. We could try and add `turn_sign_map` to `that.skip` [here](https://github.com/graphhopper/directions-api-js-client/blob/0dd130386dfbe132834a00f0d169ce81d3fe73c4/src/GraphHopperRouting.js#L144).

**Comment by karussell** [comment]
Yes, and also this graphhopper maps host. Will try.

**Comment by karussell** [comment]
Seems to work - thanks!

**Comment by karussell** [comment]
How do I release this to npm?

**Comment by boldtrn** [comment]
Do you have a npmjs.com account? I can add you to the repository or I can release it?

**Comment by karussell** [comment]
> I can add you to the repository or I can release it?

Would you mind to do both :D ?
