### ISSUE TITLE
Create unit test infrastructure

### ISSUE THREAD

**Issue by karussell** [graphhopper/directions-api-js-client#5]
Important to avoid reoccurrence of problems

**Comment by oblonski** [comment]
This is important. I aggree.

Am 16/07/15 um 09:16 schrieb Peter:

**Comment by karussell** [comment]
Can run the unit tests now via opening SpecRunner.html

**Comment by oblonski** [comment]
ohh. das ist ja cool :).


Am 16/07/15 um 14:56 schrieb Peter:
