### ISSUE TITLE
How can I use this library in Angular?

### ISSUE THREAD

**Issue by JeongJun-Lee** [graphhopper/directions-api-js-client#54]
Hello,

By the guideline, I did like below:

1. Install
npm install graphhopper-js-api-client --save

2. Import libs I need only 
import * as GraphHopperRouting from 'graphhopper-js-api-client/src/GraphHopperRouting';
import * as GHInput from 'graphhopper-js-api-client/src/GHInput';

3. Call functions
     var ghRouting = new GraphHopperRouting({key: 'defaultKey', host: 'host', vehicle: 'car', elevation: false});
 
     // Setup your own Points
     ghRouting.addPoint(new GHInput(47.400905, 8.534317));
     ghRouting.addPoint(new GHInput(47.394108, 8.538265));

4. Error comes out
`Uncaught ReferenceError: GraphHopperRouting is not defined
    at Object../node_modules/graphhopper-js-api-client/src/GraphHopperRouting.js (GraphHopperRouting.js:7)
    at __webpack_require__ (bootstrap:84)`

**Comment by JeongJun-Lee** [comment]
For a usage in Angular, I upgrade some class to es6. Try it with https://github.com/JeongJun-Lee/directions-api-js-client

**Comment by mkbctrl** [comment]
@JeongJun-Lee since you were working in Angular, do you had any issues with Typescript there? I am planning to use it in Vue with typescript, but I don't see any @types package

**Comment by karussell** [comment]
@JeongJun-Lee thanks! If you think this would be a valuable contribution - feel free to submit a pull request :)
