### ISSUE TITLE
Alternative for Google's distance matrix?

### ISSUE THREAD

**Issue by vespino** [graphhopper/directions-api-js-client#8]
I'm currently using Google's distance matrix to find distances between 1 point and many points. I'm using PHP to do so. Can I use your service as a replacement seeing my app already reaches the max request limit and I'm only just testing :)

If yes, do you have a PHP example which replaces this?

https://developers.google.com/maps/documentation/distancematrix/intro#DistanceMatrixResponses

Thanks in advance.

**Comment by karussell** [comment]
Yes, sure you can use our Matrix API. But sorry, we can do this but currently only offer [JavaScript and Java clients](https://github.com/graphhopper/directions-api#api-clients-and-examples) including simple demos.

See the [JSON response](https://github.com/graphhopper/directions-api/blob/master/docs-matrix.md#matrix-api) from the API.

Let me know if this helps you further!

**Comment by vespino** [comment]
And it's totally free?

**Comment by vespino** [comment]
Thanks, but I'm looking for a free solution without limitations.
